// components/UnitListRow.tsx
import React, { useState, useEffect } from 'react';
import { Unit } from '../types';
import { CONFIG } from '../config';
import { formatPrice } from './UnitCard';
import { IconBed, IconBath, IconCar, IconSize, IconLayout, IconHeart } from './Icons';
import { getViewersForUnit, subscribeToViewersUpdates } from '../services/viewersStore';

interface UnitListRowProps {
  unit: Unit;
  onSelect: (unit: Unit) => void;
  onReserve: (unit: Unit) => void;
  isWishlisted: boolean;
  onToggleWishlist: (unitId: string) => void;
  isAdmin?: boolean;
  /** When true (e.g. on My Reservations page), show full opacity so the unit is visible. Buttons stay disabled. */
  hideReservedOverlay?: boolean;
  serverClockOffsetMs?: number;
}

export const UnitListRow: React.FC<UnitListRowProps> = ({ unit, onSelect, onReserve, isWishlisted, onToggleWishlist, isAdmin = false, hideReservedOverlay = false, serverClockOffsetMs = 0 }) => {
  const [timeLeft, setTimeLeft] = useState<number>(0);
  const [, setTick] = useState(0);
  const viewers = getViewersForUnit(unit.id) || unit.viewers || {};

  useEffect(() => {
    return subscribeToViewersUpdates(() => setTick((t) => t + 1));
  }, []);

  useEffect(() => {
    if (!unit.lockExpiresAt) {
      setTimeLeft(0);
    } else {
      const effectiveNow = () => Date.now() + serverClockOffsetMs;
      const updateTimer = () => {
        const remaining = Math.max(0, Math.floor((unit.lockExpiresAt! - effectiveNow()) / 1000));
        setTimeLeft(remaining);
      };
      updateTimer();
      const interval = setInterval(updateTimer, 1000);
      return () => clearInterval(interval);
    }
  }, [unit.lockExpiresAt, serverClockOffsetMs]);

  useEffect(() => {
    const presenceTicker = setInterval(() => {
      setTick(t => t + 1);
    }, CONFIG.PRESENCE_TICK_MS);
    return () => clearInterval(presenceTicker);
  }, []);

  const isLocked = timeLeft > 0 && unit.status === 'Available';
  const isAvailable = unit.status === 'Available' && !isLocked;
  const showDimmed = !isAvailable && !isAdmin && !hideReservedOverlay;

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const getStatusText = () => {
    if (unit.status === 'Sold') return `Unit ${unit.unitNumber} is Sold`;
    if (unit.status === 'Reserved') return `Unit ${unit.unitNumber} is Reserved`;
    if (isLocked) return `Reservation in progress (${formatTime(timeLeft)})`;
    
    const count = Object.keys(viewers).length;
    return `${count} currently viewing`;
  };

  const getIndicatorColorClass = () => {
    if (unit.status === 'Sold') return 'bg-red-500';
    if (unit.status === 'Reserved') return 'bg-amber-500';
    if (isLocked) return 'bg-orange-500 shadow-[0_0_8px_rgba(249,115,22,0.6)] animate-pulse';
    return 'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)] animate-pulse';
  };

  const getBadgeStyles = () => {
    if (unit.status === 'Sold') return 'text-red-500 border-red-500/30';
    if (unit.status === 'Reserved') return 'text-amber-500 border-amber-500/30';
    if (isLocked) return 'text-orange-500 border-orange-500/30 bg-orange-500/10';
    return 'text-zinc-500 border-white/10';
  };

  return (
    <div 
      className={`relative liquid-glass rounded-xl p-4 sm:px-6 sm:py-0 sm:h-24 mb-4 flex items-center overflow-hidden border-none transition-all duration-500 bg-clip-padding cursor-default ${(isAvailable || isAdmin) ? 'hover:bg-white/[0.05]' : ''}`}
    >
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between transition-all duration-700 w-full z-10 gap-4 sm:gap-0">
        
        {/* Unit name + price */}
        <div className={`flex items-center justify-between sm:flex-col sm:items-start w-full sm:w-auto shrink-0 sm:min-w-[10rem] lg:w-[12rem] transition-opacity duration-500 ${showDimmed ? 'opacity-20 select-none pointer-events-none' : ''}`}>
          <span className="text-base sm:text-xl font-medium text-white tracking-tight leading-none">Unit {unit.unitNumber}</span>
          <div className="text-lg sm:text-2xl font-black text-zinc-100 leading-none tracking-tight whitespace-nowrap sm:mt-2">R {formatPrice(unit.price)}</div>
        </div>
        
        {/* Specs row */}
        <div className={`flex items-center gap-x-4 sm:gap-x-6 xl:gap-x-8 shrink-0 lg:w-[24rem] transition-opacity duration-500 ${showDimmed ? 'opacity-20 select-none pointer-events-none' : ''}`}>
          <div className="flex items-center gap-1 sm:gap-1.5 text-[11px] sm:text-[12px] text-zinc-400 font-medium uppercase tracking-wider whitespace-nowrap">
            <IconBed className="w-4 h-4 sm:w-5 sm:h-5 text-zinc-500 flex-shrink-0" />
            <span>{unit.bedrooms}</span>
          </div>
          <div className="flex items-center gap-1 sm:gap-1.5 text-[11px] sm:text-[12px] text-zinc-400 font-medium uppercase tracking-wider whitespace-nowrap">
            <IconBath className="w-4 h-4 sm:w-5 sm:h-5 text-zinc-500 flex-shrink-0" />
            <span>{unit.bathrooms}</span>
          </div>
          <div className="flex items-center gap-1 sm:gap-1.5 text-[11px] sm:text-[12px] text-zinc-400 font-medium uppercase tracking-wider whitespace-nowrap">
            <IconCar className="w-4 h-4 sm:w-5 sm:h-5 text-zinc-500 flex-shrink-0" />
            <span>{unit.parking}</span>
          </div>
          <div className="flex items-center gap-1 sm:gap-1.5 text-[11px] sm:text-[12px] text-zinc-400 font-medium uppercase tracking-wider whitespace-nowrap">
            <IconLayout className="w-4 h-4 sm:w-5 sm:h-5 text-zinc-500 flex-shrink-0" />
            <span>{unit.unitType}</span>
          </div>
          <div className="flex items-center gap-1 sm:gap-1.5 text-[11px] sm:text-[12px] text-zinc-400 font-medium uppercase tracking-wider whitespace-nowrap">
            <IconSize className="w-4 h-4 sm:w-5 sm:h-5 text-zinc-500 flex-shrink-0" />
            <span>{unit.sizeSqm}<span className="lowercase">m²</span></span>
          </div>
        </div>

        {/* Status */}
        <div className={`hidden lg:flex flex-col items-start justify-center shrink-0 lg:w-[15rem] transition-opacity duration-500 ${showDimmed ? 'opacity-20 select-none pointer-events-none' : ''}`}>
          <div className="text-[10px] text-zinc-500 font-black tracking-wide flex items-center uppercase whitespace-nowrap h-4">
            <span className={`w-2 h-2 aspect-square rounded-full mr-4 flex-shrink-0 block ${getIndicatorColorClass()}`} />
            <span className={`leading-none ${isLocked ? 'text-orange-500 font-bold' : ''}`}>{getStatusText()}</span>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-3 sm:gap-6 justify-between sm:justify-end w-full sm:w-auto shrink-0 lg:w-[25rem]">
          <div className="flex items-center gap-2 sm:gap-4 flex-1 sm:flex-initial">
            <button 
              disabled={!isAvailable && !isAdmin}
              className={`flex-1 sm:flex-initial sm:w-32 lg:w-40 h-10 sm:h-[46px] border border-white/10 text-zinc-300 rounded-lg text-[10px] sm:text-[11px] font-black uppercase tracking-normal transition-all text-center whitespace-nowrap flex items-center justify-center ${showDimmed ? 'opacity-20 pointer-events-none' : 'hover:bg-white/5 hover:text-white'}`}
              onClick={(e) => { e.stopPropagation(); onSelect(unit); }}
            >
              LEARN MORE
            </button>
            
            <div className="flex-1 sm:flex-initial sm:w-32 lg:w-40 h-10 sm:h-[46px] relative">
              {isAvailable ? (
                <button 
                  className="w-full h-full bg-zinc-100 text-zinc-950 rounded-lg text-[10px] sm:text-[11px] font-black uppercase tracking-normal hover:bg-white transition-all shadow-lg text-center whitespace-nowrap flex items-center justify-center"
                  onClick={(e) => { e.stopPropagation(); onReserve(unit); }}
                >
                  RESERVE NOW
                </button>
              ) : (
                <div className={`px-2 sm:px-4 w-full h-full flex items-center justify-center rounded-lg border bg-transparent text-[9px] sm:text-[10px] font-black uppercase tracking-normal transition-all z-[110] text-center ${getBadgeStyles()}`}>
                  {isLocked ? 'RESERVING' : unit.status}
                </div>
              )}
            </div>
          </div>
          
          <button 
            disabled={!isAvailable && !isAdmin}
            className={`w-9 h-9 sm:w-[36px] sm:h-[36px] flex-shrink-0 flex items-center justify-center backdrop-blur-md rounded-full border border-white/10 transition-all ${showDimmed ? 'opacity-20 pointer-events-none' : ''} ${isWishlisted ? 'bg-red-500/20 text-red-500 border-red-500/30' : 'bg-black/40 text-zinc-400 hover:text-red-400'}`}
            onClick={(e) => { e.stopPropagation(); onToggleWishlist(unit.id); }}
          >
            <IconHeart className="w-4 h-4" filled={isWishlisted} />
          </button>
        </div>
      </div>

      <div className="absolute inset-0 z-[100] pointer-events-none rounded-xl ring-1 ring-inset ring-white/10" />
    </div>
  );
};

// frontend/components/UnitListRow.vue
<template>
  <div
    class="group relative w-full overflow-hidden select-none cursor-default bg-white border border-zinc-100 shadow-[0_1px_2px_rgba(0,0,0,0.04)] transition-all duration-300 rounded-[0.75rem]"
    :class="(isAvailable || isAdmin) ? 'hover:shadow-[0_2px_10px_rgba(0,0,0,0.06)]' : ''"
  >
    <!-- Mobile layout: EXACT Grid UnitCard layout (no image) -->
    <div class="sm:hidden">
      <!-- Unit number + wishlist pill -->
      <div class="flex items-start justify-between px-4 pt-4 pb-0 pointer-events-none">
        <span class="pointer-events-auto text-lg font-bold text-zinc-900 tracking-tight leading-none">
          {{ unit.unitNumber }}
        </span>
        <button
          type="button"
          :disabled="!isAvailable && !isAdmin"
          class="pointer-events-auto inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-full border border-zinc-300 bg-white/95 text-zinc-600 text-[10px] font-bold uppercase tracking-widest shadow-sm transition-[background-color,color,border-color] duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] hover:bg-red-600 hover:text-white hover:border-red-600 disabled:opacity-50 disabled:pointer-events-none disabled:text-zinc-400 disabled:hover:bg-white/95 disabled:hover:text-zinc-400 disabled:hover:border-zinc-300"
          :class="isWishlisted ? '!border-red-600 !bg-red-600 !text-white' : ''"
          @click.stop="onToggleWishlist(unit.id)"
        >
          <IconHeart class="w-[0.6rem] h-[0.6rem] flex-shrink-0" :filled="isWishlisted" />
          Wishlist
        </button>
      </div>

      <!-- Details section (same spacing/typography as UnitCard) -->
      <div class="px-4">
        <div class="flex justify-between items-end gap-4 pt-0 pb-4">
          <div class="min-w-0">
            <p v-if="unit.floor" class="text-[12px] sm:text-[14px] font-bold text-zinc-900 uppercase tracking-wide leading-tight">
              {{ (unit.floor || '').toUpperCase() }} FLOOR
            </p>
            <p v-if="unit.direction" class="text-[12px] text-zinc-700 mt-0.5 leading-tight">
              {{ unit.direction }} Facing
            </p>
          </div>
          <div class="text-right shrink-0">
            <p v-if="unit.originalPrice" class="text-[11px] text-zinc-400 line-through leading-tight">
              R {{ formattedOriginalPrice }}
            </p>
            <span class="text-[20px] sm:text-[26px] font-bold leading-none block text-zinc-900">
              R {{ formattedPrice }}
            </span>
          </div>
        </div>

        <!-- Feature icons (same markup/classes as UnitCard) -->
        <div class="flex items-center justify-evenly gap-4 border-t border-b border-zinc-200/80 py-4">
          <div class="group/tip relative inline-flex flex-col items-center gap-1 cursor-help text-[11px] text-zinc-700">
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
              Bedrooms
              <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
            </span>
            <IconBed class="w-4 h-4 text-zinc-700 flex-shrink-0" />
            <span>{{ unit.bedrooms }}</span>
          </div>
          <div class="group/tip relative inline-flex flex-col items-center gap-1 cursor-help text-[11px] text-zinc-700">
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
              Bathrooms
              <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
            </span>
            <IconBath class="w-4 h-4 text-zinc-700 flex-shrink-0" />
            <span>{{ unit.bathrooms }}</span>
          </div>
          <div class="group/tip relative inline-flex flex-col items-center gap-1 cursor-help text-[11px] text-zinc-700">
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
              Parking
              <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
            </span>
            <IconCar class="w-4 h-4 text-zinc-700 flex-shrink-0" />
            <span>{{ unit.parking }}</span>
          </div>
          <div class="group/tip relative inline-flex flex-col items-center gap-1 cursor-help text-[11px] text-zinc-700">
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
              Unit Type
              <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
            </span>
            <IconLayout class="w-4 h-4 text-zinc-700 flex-shrink-0" />
            <span>{{ unit.unitType || '—' }}</span>
          </div>
          <div class="group/tip relative inline-flex flex-col items-center gap-1 cursor-help text-[11px] text-zinc-700">
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
              Unit Size
              <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
            </span>
            <IconSize class="w-4 h-4 text-zinc-700 flex-shrink-0" />
            <span>{{ unit.sizeSqm }}m²</span>
          </div>
        </div>
      </div>

      <!-- Bottom buttons (same classes as UnitCard two-button row) -->
      <div class="grid grid-cols-2 border-zinc-200/80">
        <button
          type="button"
          :disabled="!isAvailable && !isAdmin"
          class="-mt-px pt-[calc(1rem+1px)] pb-4 text-[12px] font-bold uppercase tracking-widest bg-transparent text-zinc-900 hover:bg-[#18181B] hover:text-white transition-[background-color,color] duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] disabled:opacity-50 disabled:pointer-events-none disabled:text-zinc-500 disabled:hover:bg-transparent text-center w-full"
          @click.stop="onSelect(unit)"
        >
          View Details
        </button>
        <button
          type="button"
          :disabled="(!isAvailable && !isAdmin) || isReserving"
          class="-mt-px -ml-px pl-px pt-[calc(1rem+1px)] pb-4 text-[12px] font-bold uppercase tracking-widest bg-transparent text-zinc-900 border-l border-zinc-200/80 hover:bg-[#18181B] hover:text-white transition-[background-color,color] duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] disabled:opacity-50 disabled:pointer-events-none disabled:text-zinc-500 disabled:hover:bg-transparent text-center"
          @click.stop="onReserve(unit)"
        >
          {{ reserveButtonLabel }}
        </button>
      </div>
    </div>

    <!-- Desktop/tablet layout (original list row) -->
    <div class="hidden sm:flex sm:flex-col sm:grid sm:grid-cols-3 sm:items-center gap-4 sm:gap-0 px-4 sm:px-6 py-6">
      <!-- Left: unit + floor + direction on one line, price below -->
      <div class="min-w-0 flex flex-col gap-2 flex-shrink-0 sm:pr-6">
        <div class="flex flex-wrap items-baseline gap-x-4 gap-y-0 leading-tight">
          <span class="text-[14px] font-extrabold tracking-[0.22em] uppercase text-zinc-900">
            Unit {{ unit.unitNumber }}
          </span>
          <span class="inline-flex items-baseline gap-x-1 text-[12px]">
            <span v-if="unit.floor" class="font-semibold text-zinc-600">
              {{ formatFloorLabel(unit.floor) }}
            </span>
            <span v-if="unit.floor && unit.direction" class="text-zinc-300" aria-hidden="true">•</span>
            <span v-if="unit.direction" class="font-semibold text-zinc-600">
              {{ formatFacingLabel(unit.direction) }}
            </span>
          </span>
        </div>
        <div class="text-left">
          <p v-if="unit.originalPrice" class="text-[11px] text-zinc-400 line-through leading-tight">
            R {{ formattedOriginalPrice }}
          </p>
          <p class="text-[20px] sm:text-[24px] font-bold leading-none text-zinc-900">
            R {{ formattedPrice }}
          </p>
        </div>
      </div>

      <!-- Middle: icons -->
      <div class="flex items-center justify-center gap-6 sm:gap-14 border-t sm:border-t-0 border-zinc-200/80 pt-4 sm:pt-0 sm:px-6 min-w-0">
        <div class="group/tip relative inline-flex items-center gap-2 cursor-help text-[12px] text-zinc-700">
          <span class="sr-only">Bedrooms</span>
          <IconBed class="w-4 h-4 text-zinc-700 flex-shrink-0" />
          <span class="font-semibold">{{ unit.bedrooms }}</span>
          <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
            Bedrooms
            <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
          </span>
        </div>
        <div class="group/tip relative inline-flex items-center gap-2 cursor-help text-[12px] text-zinc-700">
          <span class="sr-only">Bathrooms</span>
          <IconBath class="w-4 h-4 text-zinc-700 flex-shrink-0" />
          <span class="font-semibold">{{ unit.bathrooms }}</span>
          <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
            Bathrooms
            <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
          </span>
        </div>
        <div class="group/tip relative inline-flex items-center gap-2 cursor-help text-[12px] text-zinc-700">
          <span class="sr-only">Parking</span>
          <IconCar class="w-4 h-4 text-zinc-700 flex-shrink-0" />
          <span class="font-semibold">{{ unit.parking }}</span>
          <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
            Parking
            <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
          </span>
        </div>
        <div class="group/tip relative inline-flex items-center gap-2 cursor-help text-[12px] text-zinc-700">
          <span class="sr-only">Unit Type</span>
          <IconLayout class="w-4 h-4 text-zinc-700 flex-shrink-0" />
          <span class="font-semibold">{{ unit.unitType || '—' }}</span>
          <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
            Unit Type
            <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
          </span>
        </div>
        <div class="group/tip relative inline-flex items-center gap-2 cursor-help text-[12px] text-zinc-700">
          <span class="sr-only">Unit Size</span>
          <IconSize class="w-4 h-4 text-zinc-700 flex-shrink-0" />
          <span class="font-semibold">{{ unit.sizeSqm }}m²</span>
          <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2.5 py-1.5 bg-zinc-800 text-white text-[11px] rounded opacity-0 pointer-events-none transition-opacity z-20 whitespace-nowrap group-hover/tip:opacity-100">
            Unit Size
            <span class="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-zinc-800" aria-hidden="true" />
          </span>
        </div>
      </div>

      <!-- Right: actions -->
      <div class="flex items-center justify-end gap-3 sm:gap-4 w-full sm:w-auto border-t sm:border-t-0 pt-4 sm:pt-0 flex-shrink-0 sm:pl-6">
        <div class="flex items-center gap-3 sm:gap-4">
          <button
            type="button"
            :disabled="!isAvailable && !isAdmin"
            class="h-[46px] min-w-[140px] px-6 text-[12px] font-bold uppercase tracking-widest bg-transparent text-zinc-900 rounded-lg hover:bg-[#18181B] hover:text-white hover:rounded-lg transition-[background-color,color,border-radius] duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] disabled:opacity-50 disabled:pointer-events-none disabled:text-zinc-500 disabled:hover:bg-transparent text-center"
            @click.stop="onSelect(unit)"
          >
            View Details
          </button>
          <span class="h-5 w-px bg-zinc-200/80" aria-hidden="true" />
          <button
            type="button"
            :disabled="(!isAvailable && !isAdmin) || isReserving"
            class="h-[46px] min-w-[150px] px-6 text-[12px] font-bold uppercase tracking-widest bg-transparent text-zinc-900 rounded-lg hover:bg-[#18181B] hover:text-white hover:rounded-lg transition-[background-color,color,border-radius] duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] disabled:opacity-50 disabled:pointer-events-none disabled:text-zinc-500 disabled:hover:bg-transparent text-center"
            @click.stop="onReserve(unit)"
          >
            {{ reserveButtonLabel }}
          </button>
          <button
            type="button"
            :disabled="!isAvailable && !isAdmin"
            class="hidden sm:inline-flex h-9 w-9 items-center justify-center rounded-full border border-zinc-300 bg-white/95 text-zinc-600 transition-[background-color,color,border-color] duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] hover:bg-red-600 hover:text-white hover:border-red-600 disabled:opacity-50 disabled:pointer-events-none disabled:text-zinc-400 disabled:hover:bg-white/95 disabled:hover:text-zinc-400 disabled:hover:border-zinc-300"
            :class="isWishlisted ? '!border-red-600 !bg-red-600 !text-white' : ''"
            aria-label="Toggle wishlist"
            @click.stop="onToggleWishlist(unit.id)"
          >
            <IconHeart class="w-4 h-4" :filled="isWishlisted" />
          </button>
        </div>
      </div>
    </div>

    <!-- Reserved/Sold/Locked banner (no unit type image in list view) -->
    <div v-if="showOverlay" class="absolute inset-0 flex items-center justify-center pointer-events-none bg-white/60 backdrop-blur-[1px]">
      <span class="px-7 py-2 rounded-full bg-zinc-900 text-white text-[11px] font-black uppercase tracking-[0.2em]">
        {{ overlayLabel }}
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Unit } from '~/types'
import IconBed from '~/components/icons/IconBed.vue'
import IconBath from '~/components/icons/IconBath.vue'
import IconCar from '~/components/icons/IconCar.vue'
import IconSize from '~/components/icons/IconSize.vue'
import IconLayout from '~/components/icons/IconLayout.vue'
import IconHeart from '~/components/icons/IconHeart.vue'

const props = withDefaults(
  defineProps<{
    unit: Unit
    isWishlisted?: boolean
    isAdmin?: boolean
    hideReservedOverlay?: boolean
    serverClockOffsetMs?: number
    currentUserId?: string | null
    reservingUnitId?: string | null
  }>(),
  { isWishlisted: false, isAdmin: false, hideReservedOverlay: false, serverClockOffsetMs: 0, currentUserId: undefined, reservingUnitId: null },
)

const emit = defineEmits<{
  select: [unit: Unit]
  reserve: [unit: Unit]
  toggleWishlist: [unitId: string]
}>()

const timeLeft = ref(0)
const isLocked = computed(() => timeLeft.value > 0 && props.unit.status === 'Available')
const isReserving = computed(() => props.reservingUnitId === props.unit.id)
const isAvailable = computed(() => props.unit.status === 'Available' && !isLocked.value)

const showOverlay = computed(() =>
  !props.isAdmin &&
  !props.hideReservedOverlay &&
  (props.unit.status !== 'Available' || isLocked.value),
)

const formattedPrice = computed(() =>
  new Intl.NumberFormat('en-US').format(props.unit.price).replace(/,/g, ' '),
)
const formattedOriginalPrice = computed(() =>
  props.unit.originalPrice
    ? new Intl.NumberFormat('en-US').format(props.unit.originalPrice).replace(/,/g, ' ')
    : '',
)

const reserveButtonLabel = computed(() => {
  if (isReserving.value) return 'Securing...'
  if (props.unit.status === 'Available' && !isLocked.value) return 'Reserve Now'
  if (isLocked.value) return 'Locked'
  return props.unit.status
})

const overlayLabel = computed(() => {
  if (isLocked.value) return 'Reservation In Progress'
  return props.unit.status
})

function formatFloorLabel(floor: string | null | undefined): string {
  const raw = (floor || '').trim()
  if (!raw) return ''
  const lower = raw.toLowerCase()
  const withFloor = lower.includes('floor') ? lower : `${lower} floor`
  return withFloor.replace(/\b\w/g, (c) => c.toUpperCase())
}

function formatFacingLabel(direction: string | null | undefined): string {
  const raw = (direction || '').trim()
  if (!raw) return ''
  const lower = raw.toLowerCase()
  const withFacing = lower.includes('facing') ? lower : `${lower} facing`
  return withFacing.replace(/\b\w/g, (c) => c.toUpperCase())
}

function onSelect(unit: Unit) {
  if (!isAvailable.value && !props.isAdmin) return
  emit('select', unit)
}

function onReserve(unit: Unit) {
  if (!isAvailable.value && !props.isAdmin) return
  emit('reserve', unit)
}

function onToggleWishlist(unitId: string) {
  emit('toggleWishlist', unitId)
}

let timerId: ReturnType<typeof setInterval> | null = null
function startTimer() {
  if (!props.unit.lockExpiresAt) {
    timeLeft.value = 0
    return
  }
  const effectiveNow = () => Date.now() + props.serverClockOffsetMs
  const update = () => {
    timeLeft.value = Math.max(0, Math.floor((props.unit.lockExpiresAt! - effectiveNow()) / 1000))
  }
  update()
  timerId = setInterval(update, 1000)
}

onMounted(() => { startTimer() })
onBeforeUnmount(() => { if (timerId) clearInterval(timerId) })
watch(() => [props.unit.lockExpiresAt, props.serverClockOffsetMs], () => {
  if (timerId) clearInterval(timerId)
  timerId = null
  startTimer()
})
</script>
